title: "Katherine's Portfolio"
author: "Katherine"
description: "Data Engineer | AI Enthusiast | Community Builder"
remote_theme: pages-themes/cayman@v0.2.0
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - blog.md
  - projects.md
